export interface  getApprovalBeats{
    ApprovedDate: number,
    BeatId: number,
    CreatedBy: number,
    DeviceId:string,
    Devicename: string,
    EmailWhoInsert: string,
    EndTime: number,
    End_Lat: number,
    End_Lon: number,
    ExistingBeatId: number,
    KmEnd: string,
    KmStart: string,
    MobWhoInsert: string,
    NameWhoInsert:string,
    SectionName: string,
    Start_Lat: number,
    Start_Lon: number,
    UpdatedBy: number,
    UserLoginId: number,
    activeStatus: number,
    beatId: number,
    id: number,
    isApprove: boolean,
    parentId: number,
    startTime: number,
    studentId: number
}

export interface getPatrolmenBeats{
    deviceName: string,
    kmEnd: string,
    kmStart: string,
    sectionName: string,
    seasonId: string,
    studentId: number,
    tripId: number,
    ApprovedDate: string,
        tripTime :{
            endTime: number,
            startTime: number,
            fk_TripMasterId: number,
            isApprove: boolean,
            tripId: number
        },
}